### ISSUE TITLE
Yarn 2

### ISSUE THREAD

**Issue by arcanis** [azukaar/GuPM#31]
Hey, I saw your work on Reddit and after taking a look at your selling points I figured I should drop you a word (I'm Yarn's lead maintainer).

[Yarn 2](https://github.com/yarnpkg/yarn/issues/6953), started a few months ago, supports plugins. More importantly, it supports what we call custom linkers - the idea is that we can install packages in various shape. For Node it would be a node_modules, for PHP an autoload, for Python something else, etc. Which, correct me if I'm wrong, sounds a lot like the reason why you built GuPM.

Since we know what we do in term of user experience (workspaces, resolutions field, the various upgrade workflow, PnP, etc) but we lack some manpower to target other languages than JavaScript, I wonder whether it would make sense for you to join us on this journey rather than creating a all-new package manager. It doesn't really make sense to reimplement the boring lockfile details and all if what you care about is porting the Yarn workflow to other languages.

You obviously spent a lot of time on this project so I would totally understand if you decided to continue your way; I just wanted to let you know you're not alone in this 🙂

Feel free to ping me on the [Yarn Discord](https://discordapp.com/invite/yarnpkg) if you want to discuss it in a more dynamic way than Github issues, I'd be happy to tell you more about our work so far. If anything, it may help you in your futur endeavours.

**Comment by azukaar** [comment]
Will contact you on The Discord!
